rabbit_host = '10.128.0.6'
rabbit_user = 'monitoring_user'
rabbit_password = 'isis2503'
exchange = 'clientes_exchange'
exchange = 'clientes_exchange'
routing_key='clientes_routing_key'
queue_name = 'clientes_queue'